trigger:
  - master

pool:
  vmImage: "windows-latest"

variables:
  ARTIFACT_NAME: DevelopMomentumWeb

stages:
  - stage: Release
    displayName: Release

    jobs:
      - deployment: DeployToStorage
        displayName: Deploy to Azure Storage