trigger:
  - master

pool:
  vmImage: "windows-latest"

variables:
  ARTIFACT_NAME: DevelopMomentumWeb

stages:
  - stage: Build
    displayName: Build

    jobs:
      - job: Transform
        displayName: Transform Input

  - stage: Release
    displayName: Release
    dependsOn: Build

    jobs:
      - deployment: DeployToStorage
        displayName: Deploy to Azure Storage